spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    name: user
    password: test123
    driverClassName: com.mysql.cj.jdbc.Driver

  config:
    import: "optional:configserver:http://localhost:8088"


server:
  port: 8091