server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  web:
    jwtSecret: WERGEW4v23v34revr34v345v3425v342v5324v52fkewmq4ior334joi3jntio3ij4iionj4io3jtio4f34r3243rwrqQWRqwGQfwqq3rqFQWEF
    jwtExpirationms: 24000000
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: listing-service
          uri: lb://listing-service
          predicates:
            - Path=/realestates/**,/admin/realestate/**
          filters:
            - AuthenticationFilter
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/photo/**
          filter :
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/user/**
          filters:
            - AuthenticationFilter
        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/finance/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter

