server:
  port: 8088

spring:
  profiles:
    active: native


#  application:
#    datasource:
#      url: jdbc:mysql://localhost:3306/product_service
#      name: user
#      password: test123
#      driver-class-name: com.mysql.cj.jdbc.Driver