spring:
  application:
    name: listing-service
  datasource:
    url: jdbc:mysql://localhost:3306/listing_service
    name: root
    password: 123456789
    driverClassName: com.mysql.cj.jdbc.Driver

  config:
    import: "optional:configserver:http://localhost:8088"
  web:
    jwtSecret: WERGEW4v23v34revr34v345v3425v342v5324v52fkewmq4ior334joi3jntio3ij4iionj4io3jtio4f34r3243rwrqQWRqwGQfwqq3rqFQWEF
    jwtExpirationms: 24000000

  multipart:
    enabled: true
    max-file-size: 300MB
    file-size-threshold: 2KB
    max-request-size: 300MB
rabbitmq:
  exchange:
    name: LISTING_TO_PAYMENT_EXCHANGE

  routing:
    json:
      key: LISTING_TO_PAYMENT_KEY
  queue:
    name: LISTING_TO_PAYMENT_QUEUE
server:
  port: 8091