spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    name: duan2
    password: test123
    driverClassName: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:8088"
server:
  port: 8100