spring:
  application:
    name: listing-service
  datasource:
    url: jdbc:mysql://localhost:3306/listing_service
    name: user
    password: test123
    driverClassName: com.mysql.cj.jdbc.Driver

  config:
    import: "optional:configserver:http://localhost:8088"
  web:
    jwtSecret: WERGEW4v23v34revr34v345v3425v342v5324v52fkewmq4ior334joi3jntio3ij4iionj4io3jtio4f34r3243rwrqQWRqwGQfwqq3rqFQWEF
    jwtExpirationms: 24000000


server:
  port: 8091